Repository fga-gpp-mds/2018.1-Dulce_API, pull requests merged in 2018-04, with the labels that each got.

#8 Fix #1 Criar usuário gestor
  criarGestor/.gitignore
  criarGestor/Dockerfile
  criarGestor/app/app.js
  criarGestor/app/package.json
  criarGestor/docker-compose.yml
Labels: arquitetura, avançado, correção, dulce

#6 Fix #3 visualizar gestor
  visualizarGestor/Dockerfile
  visualizarGestor/app/app.js
  visualizarGestor/app/package.json
  visualizarGestor/docker-compose.yml
Labels: arquitetura, avançado, dulce, evolução

#18 Fix #17 refatorar apis
  User/Dockerfile
  User/app/Components/allUsers.js
  User/app/Components/editUser.js
  User/app/Components/login.js
  User/app/Components/model/user.js
  User/app/Components/newUser.js
  User/app/Components/viewUser.js
  User/app/Makefile
  User/app/app.js
  User/app/package.json
  User/app/test/app.test.js
  User/docker-compose.yml
  criarGestor/.gitignore
  criarGestor/app/app.js
  criarGestor/app/package-lock.json
  criarGestor/app/package.json
  criarGestor/docker-compose.yml
  editarGestor/Dockerfile
  editarGestor/app/app.js
  editarGestor/app/package-lock.json
  editarGestor/app/package.json
  editarGestor/docker-compose.yml
  login/Dockerfile
  login/app/app.js
  login/app/user.js
  visualizarGestor/Dockerfile
  visualizarGestor/app/app.js
  visualizarGestor/app/package-lock.json
  visualizarGestor/app/package.json
  visualizarGestor/docker-compose.yml
Labels: api, correção, evolução

#21 Fix #15 cobertura de testes
  User/app/Components/allUsers.js
  User/app/Components/login.js
  User/app/app.js
  User/app/package.json
  User/app/test/app.test.js
Labels: MDS, Teste, api, intermediario, manutenção

#33 HOTFIX #29 visualizar setores
  Sector/.gitignore
  Sector/Client/Dockerfile
  Sector/Client/api.js
  Sector/Client/client_sector.js
  Sector/Client/package.json
  Sector/Client/test/sector.test.js
  Sector/Server/Dockerfile
  Sector/Server/package.json
  Sector/Server/sector.js
  Sector/docker-compose.yml
  package-lock.json
  src/img/EditUserFailed.jpg
  src/img/EditUserSucess.jpg
  src/img/PostmanAdd.png
  src/img/PostmanListFail.png
  src/img/PostmanListSucess.png
  src/img/PostmanLogin.jpg
  src/img/PostmanViewFailed.png
  src/img/PostmanViewSucess.png
Labels: 0-Developers, 0-MDS, 2-Feature, 3-História de Usuário, 5-Intermediário
